name: Deploy Auth Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'auth-frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'auth-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'auth-frontend/package-lock.json'
      
      - name: Install dependencies
        working-directory: auth-frontend
        run: npm ci
      
      - name: Build application
        working-directory: auth-frontend
        run: npm run build
        env:
          VITE_API_URL: https://api.axionshosting.com
          VITE_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      
      - name: Deploy to Cloudflare Pages
        if: github.event_name == 'push'
        working-directory: auth-frontend
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            npm run deploy
          else
            npm run deploy:staging
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}